library(mlr)
library(plyr)
library(dplyr)
library(caret)
library(pROC)
library(corrplot)
library(psych)
dfDonations <- read.table("training_data.csv",sep=",",header=TRUE)
dim(dfDonations)
summary(dfDonations)
str(dfDonations)
multi.hist(dfDonations)
summarizeColumns(dfDonations)